transloadit/uppy.io

- docs/uppy-core.mdx
Hi,
This is related to https://github.com/transloadit/uppy/pull/3898
When a user do a retry-all no upload-retry event is triggered. (I had to debug this)
The retry-all event is not documented and I think behavior is unexpected (not triggering upload-retry at all)
This at least document current the behavior.
Thanks.
Luc
> Fix documentation on retry-all vs upload-retry

- docs/sources/companion-plugins/box.mdx
- docs/sources/companion-plugins/dropbox.mdx
- docs/sources/companion-plugins/facebook.mdx
- docs/sources/companion-plugins/google-drive.mdx
- docs/sources/companion-plugins/instagram.mdx
- docs/sources/companion-plugins/onedrive.mdx
- docs/sources/companion-plugins/unsplash.mdx
- docs/sources/companion-plugins/url.mdx
- docs/sources/companion-plugins/zoom.mdx
- docs/sources/screen-capture.mdx
- docs/sources/webcam.mdx
- docs/uppy-core.mdx
- docs/user-interfaces/dashboard.mdx
- docs/user-interfaces/drag-drop.mdx
- docs/user-interfaces/elements/image-editor.mdx
- docs/user-interfaces/elements/informer.mdx
- docs/user-interfaces/elements/progress-bar.mdx
- docs/user-interfaces/elements/status-bar.mdx
- docs/user-interfaces/elements/thumbnail-generator.mdx
Typically, the capitalised version (e.g. `String`) refers to instances of the class (e.g. `new String`), when in fact the docs mean to refer to the primitive type (e.g. `'a primitive string'`).
> Fix casing of types in docs

- docs/uppy-core.mdx
We use `js` instead of `javascript` for code blocks everywhere else, let's choose consistency.
Add an empty line to separate markdown from raw HTML to maximise compat.
> @uppy/core: editorial changes

- docs/companion.md
from https://github.com/transloadit/uppy/pull/4382
Also re-add `COMPANION_REDIS_EXPRESS_SESSION_PREFIX` - it was introduced in https://github.com/transloadit/uppy.io/pull/5 (https://github.com/transloadit/uppy.io/pull/5/commits/d890cb4d891f4e96705d73a7ce8fe07424c6b7c1) but somehow it's now gone. (could other things be gone as well in a botched merge?)
also add "This is a standalone-only option" to all standalone-only options. it was only added to one of them.
> add docs for the new COMPANION_REDIS_PUBSUB_SCOPE

- .github/workflows/linters.yml
- .github/workflows/test.yml
Merge Queues will run the checks on the commit that's about to merge to target branch, and will abort if a failure is detected. The difference with auto-merges is that the checks are re-run just before merging, while auto-merges behaves as if the target branch have not changed since the checks was last run.
> experiment with Merge Queues

- docs/sources/companion-plugins/instagram.mdx
- docs/sources/companion-plugins/onedrive.mdx
In the Companion docs, the Instagram and OneDrive plugins specified Google plugin environment variables. This PR fixes those env var references.
> Fix plugin environment variable names

- docs/uploader/aws-s3-multipart.mdx
- docs/uploader/aws-s3.mdx
Refs: https://github.com/transloadit/uppy/pull/4205
Refs: https://github.com/transloadit/uppy/pull/4299
> aws-s3(-multipart): add new options

- src/css/custom.css
- src/pages/examples.module.css
- src/pages/examples.tsx
- src/pages/index.module.css
- src/theme/BlogPostItem/Footer/index.js
- src/theme/BlogPostItem/Footer/styles.module.css
Make the typography consistent again. I naively made this website only for desktop sizes which are around my laptop size, but in screenshares I've seen that on @arturi's laptop the typography is too big. Artur later implemented some fixes to make things a bit smaller here and there, but this became a bit inconsistent in my opinion. Instead, everything is now base font size but between 1000 and 1300px laptop screens the base font size is decreased, making it overall more fitting.
I also updated the blog post footer links:
> Consistent typography

- docs/uploader/aws-s3.mdx
In the AWS S3 uploader documentation, there is a broken link which references an `aws-presigned-url` example which does not exist.
I have replaced this link with one to the `aws-php` example, which also implements the server-side and client-side usage of AWS S3 presigned URLs as the `aws-presigned-url` example was claimed to do.
> Replace broken link to aws-presigned-url example

- docs/golden-retriever.mdx
According to https://github.com/transloadit/uppy/issues/4518#issuecomment-1602211752 this value is not configurable. 
This PR corrects the docs to remove the suggestion that the value is configurable.
> Remove (configurable) in Golden Retriever docs

- docs/uppy-core.mdx
---
The `reset()` method has been removed from v3, apparently: https://uppy.io/docs/guides/migration-guides/#remove-reset-method
Coming into using Uppy as a new user, I found the 'reset' function in the docs and spent way too long to figure out what and why it wasn't working 😅  Then I found the replacement (`cancelAll()`) in the migration docs.
This PR is to simply update the docs to no longer reference the `reset()` method.
Let me know if this is okay or if you prefer to keep it for now or perhaps add a message in the docs stating it's not in v3 anymore.
---
> Remove reset() method from uppy-core.mdx

- src/components/UppyCdnExample.tsx
The CDN exposes the legacy bundle under the `.js` extension, we want folks to use the `.mjs` one which contains ESM code.
> fix UppyCdnExample

- .github/workflows/update-deps.yml
Not sure why I went with `@uppy/core` originally, using the Uppy version seems much more logical.
> chore: fix auto-update workflow

- docs/uploader/aws-s3-multipart.mdx
Referencing `@uppy/aws-s3` docs won't work once we merged the two plugins, so we might as well do a bit of repetition, but that should also improve the readability of the page.
> @uppy/aws-s3-multipart: document `getUploadParameters`

- docs/uploader/aws-s3.mdx
The link in the warning on https://uppy.io/docs/aws-s3/ is broken and leads to a 404. This fixes that.
> Fix broken link in docs

- docs/user-interfaces/dashboard.mdx
Quick fix to the Dashboard docs to update the default doneButtonHandler to match the actual code.
Currently, the docs reference uppy.reset() which doesn't appear to exist.
https://github.com/transloadit/uppy/blob/3205cc3500856db7f8f3369eecc5222f914290dd/packages/%40uppy/dashboard/src/Dashboard.jsx#L69
```
doneButtonHandler: () => {
this.uppy.cancelAll()
this.requestCloseModal()
},
```
> Correct docs for Dashboard default doneButtonHandler

- src/pages/examples.tsx
- src/pages/index.tsx
enable dynamic oauth credentials fetching for google drive. this allows us to more easily spot if this implementation breaks.
note: depends on https://github.com/transloadit/uppy/pull/4667
in heroku: (replace `ADDSOMESECRETVALUEHERE` with a real random secret)
> Dynamic oauth credentials testing

- src/pages/examples.module.css
- src/pages/examples.tsx
on the examples page. note: this is a workaround and we might want to instead fix it by not using z-indexes inside uppy, but that's probably a bigger task
> fix navbar going behind uppy

- docs/companion.md
see https://github.com/transloadit/uppy/pull/4770
> Companion: document new arguments for s3.bucket and s3.getKey

- docusaurus.config.js
- package.json
- tsconfig.json
- yarn.lock
https://docusaurus.io/docs/migration/v3
> Upgrade to Docusaurus V3

- docs/sources/file-input.mdx
Fixes: https://github.com/transloadit/uppy.io/issues/186
> restore `@uppy/file-input` documentation

- docusaurus.config.js
- src/pages/privacy-policy.md
We are no longer going to use the self-hosted instance.
> update Plausible metadata

- package.json
- src/pages/examples.module.css
- src/pages/examples.tsx
- tsconfig.json
- yarn.lock
Closes #110 
Closes #119
Also fixes:
- Order of plugins are constantly changing when you check/uncheck them
- Screen Capture not working
- Golden Retriever never worked before since it would be off by default and it only shows what it does after a refresh. Persistent options fixes this too.
- Make Instagram / Facebook disabled with disabled styles for now (https://github.com/transloadit/uppy/issues/4905)
code is not pretty but it works and it's just a small page 🤷‍♂️
> Make example page options persistent

- docs/uploader/aws-s3-multipart.mdx
The first PR to change the endpoints in the documentation.
https://github.com/transloadit/uppy/blob/960362b373666b18a6970f3778ee1440176975af/packages/%40uppy/companion/src/server/controllers/s3.js#L439-L447
Related to #213
> Modify endpoints in own server section of AWS S3

- docusaurus.config.js
- src/plugins/custom.js
Webpack has a special option for handling symbolink links. Necessary to unblock https://github.com/transloadit/uppy.io/pull/217.
> meta: add custom plugin to handle symlinks

- package.json
- yarn.lock
This reverts commit 6fcf7eea02a09f79e0f2e36680af27389c730f2f.
> Revert "Bump remark-mdx from 2.3.0 to 3.0.1 (#233)"

- docusaurus.config.js
clicking "Edit this page" leads to:
clicking "Edit this page" leads to:
> docusaurus.config.js - fix all doc edit links

- README.md
Added docs about how to lint/build **uppy.io/docs** as per our Slack discussion.
> Building uppy.io/docs VS uppy.io/blog

- src/pages/examples.module.css
- src/pages/examples.tsx
Fixes https://github.com/transloadit/uppy/issues/4439
___
In general, in CSS, changes:
all tag references (e.g. `h1`),
to unique class references (e.g. `.h1_src-pages-examples-module`).
Hopefully that makes the "Uppy CSS is broken on examples page" issue appear less frequently.
> uppy.io/examples - stop css from affecting uppy

- docs/sources/companion-plugins/google-drive-picker.mdx
https://github.com/transloadit/uppy/issues/5532#issuecomment-2551335488
> fix docs for picker

- src/pages/examples.tsx
- src/pages/index.tsx
because it has been validated. this allows google photos to no longer give "app is blocked" on uppy.io
> use same transloadit oauth2 app

- docs/sources/companion-plugins/google-drive-picker.mdx
> improve picker docs

- docs/uppy-core.mdx
Actual:
```typescript
(file, files) => !Object.hasOwn(files, file.id),
```
In the documentation:
```typescript
(files, file) => !Object.hasOwn(files, file.id)
```
Source: https://github.com/transloadit/uppy/blob/main/packages/%40uppy/core/src/Uppy.ts#L436
> Fix wrong default for onBeforeFileAdded

- docs/sources/companion-plugins/dropbox.mdx
add notes about team folders
see also https://github.com/transloadit/uppy/pull/5708
> dropbox docs: explain team folders

- src/pages/examples.module.css
- src/pages/examples.tsx
Some design adjustments to the Examples page:
- Fixed label alignment when text wraps to a new line
- Renamed the "Uppy" subtitle to "Miscellaneous"
- Added a "Locale" subtitle above the locale `<select>`
- Improved the overall look and feel of the sidebar
- Fixed a typo
**Before:**
> ![Screenshot 2025-05-20 at 12 25 00@2x](https://github.com/user-attachments/assets/25035dc5-cb26-4f8f-87b3-7730e2effeec)
**After:**
> ![Screenshot 2025-05-20 at 12 25 14@2x](https://github.com/user-attachments/assets/79a63732-2dac-4f4c-bce3-f8750afea46b)
> Examples page — design tweaks

- docs/sources/companion-plugins/google-drive.mdx
Actually this might be because the app is not verified. Maybe Once the app is verified, Google will show the correct name
> Fix documentation for google drive

- docs/uppy-core.mdx
Clarified the description of the 'complete' event to specify that it refers to an upload being complete and includes information about successful and failed files.
see https://github.com/transloadit/uppy/pull/5956#discussion_r2347290975
> Clarify 'complete' event description in uppy-core.mdx

- docs/golden-retriever.mdx
Updated service worker registration to use module type. Else we get an error that we cannot use import from a cjs file
> Fix broken example
