.github/workflows/preview.yml
README.md
docusaurus.config.js

Fix Github actions preview deploy

---

docs/guides/browser-support.mdx
docs/quick-start.mdx
docs/sources/companion-plugins/box.mdx
docs/sources/companion-plugins/dropbox.mdx
docs/sources/companion-plugins/facebook.mdx
docs/sources/companion-plugins/google-drive.mdx
docs/sources/companion-plugins/instagram.mdx
docs/sources/companion-plugins/onedrive.mdx
docs/sources/companion-plugins/unsplash.mdx
docs/sources/companion-plugins/url.mdx
docs/sources/companion-plugins/zoom.mdx
docs/sources/screen-capture.mdx
docs/sources/webcam.mdx
docs/uppy-core.mdx
docs/user-interfaces/dashboard.mdx
docs/user-interfaces/drag-drop.mdx
docs/user-interfaces/elements/image-editor.mdx
docs/user-interfaces/elements/informer.mdx
docs/user-interfaces/elements/progress-bar.mdx
docs/user-interfaces/elements/status-bar.mdx
docs/user-interfaces/elements/thumbnail-generator.mdx
src/components/UppyCdnExample.tsx

see https://github.com/transloadit/uppy.io/pull/28#issuecomment-1246464822

Use module script with HTTP import for CDN examples

---

docs/guides/choosing-upload-strategy.md
docs/upload-strategies/aws-s3.md
docs/upload-strategies/aws-s3.mdx

https://transloadit.github.io/uppy.io/pr-preview/pr-35/docs/upload-strategies/aws-s3

Add AWS S3 docs

---

docs/sources/companion-plugins/facebook.mdx

see https://github.com/transloadit/uppy/pull/4172

Add note about 0Auth in Facebook docs

---

docs/uppy-core.mdx

Refs: https://github.com/transloadit/uppy/pull/4247

@uppy/xhr-upload: add `'upload-stalled'` event

---

.github/workflows/linters.yml

This should help catch instances where Prettier wasn't run on the commit hook for some reason.

add linter in GHA to check PRs and `main`

---

docusaurus.config.js
src/css/custom.css

Examples: add redirects

---

docs/framework-integrations/vue.mdx

Hey,
Thanks for the work!
The vue doc has been pasted from React one, but the example syntax is wrong 🙂.

Fix vue doc.

---

src/pages/index.module.css
src/pages/index.tsx

Fixing the Dashboard didn't play well with the pink gradient:
Also, fixing misaligned quotations here:
https://user-images.githubusercontent.com/375537/229520562-04ddb4e1-fd8f-41d8-93ab-b33b526dcd0a.mp4

Minor design fixes

---

docs/uploader/transloadit.mdx
docs/uploader/tus.mdx

Fixes: https://github.com/transloadit/uppy.io/issues/120

Fix `limit` default value in `@uppy/tus` and `@uppy/transloadit` docs

---

docs/companion.md

make it static
See https://github.com/transloadit/uppy/issues/4460

Fix authProvider doc

---

docs/uploader/aws-s3-multipart.mdx

Refs: https://github.com/transloadit/uppy/pull/4519

@uppy/aws-s3-multipart: add docs for signing on the client

---

src/pages/index.module.css
src/pages/index.tsx
src/theme/Footer/index.js
src/theme/Footer/index.module.css

also move footer to all pages
closes #134

add contributing to footer

---

docs/companion.md
docs/guides/building-plugins.md
docs/locales.mdx
docs/sources/companion-plugins/url.mdx
docs/uploader/aws-s3-multipart.mdx
docs/uploader/aws-s3.mdx
docs/uploader/transloadit.mdx
docs/uploader/tus.mdx
docs/uppy-core.mdx
docs/user-interfaces/dashboard.mdx
docs/user-interfaces/elements/thumbnail-generator.mdx

This PR fixes several typos I spotted on the website.

Fixing typos

---

docs/uploader/aws-s3-multipart.mdx

Refs: https://github.com/transloadit/uppy/pull/4614

AWS S3: add `Location` to the list of `ExposedHeaders`

---

docs/uppy-core.mdx

Ref: https://github.com/transloadit/uppy/pull/4594

Document how to allow duplicate files

---

docs/companion.md

see https://github.com/transloadit/uppy/pull/4675

companion: document enableUrlEndpoint

---

docs/golden-retriever.mdx

Closes https://github.com/transloadit/uppy.io/issues/123

Document range of storage for Golden Retriever

---

docs/companion.md

Document S3 endpoint for Companion

---

docs/sources/companion-plugins/google-drive.mdx
docs/sources/companion-plugins/instagram.mdx
docs/sources/companion-plugins/onedrive.mdx

fixes https://github.com/transloadit/uppy/issues/4363

Redirect uri fixes

---

docs/uploader/transloadit.mdx

See https://github.com/transloadit/uppy/pull/4920

Add documentation for `clientName`

---

docs/user-interfaces/dashboard.mdx

Fixes links for Facebook and Zoom documentation links

Fix documentation links

---

docs/user-interfaces/dashboard.mdx
docs/user-interfaces/elements/image-editor.mdx

___
**UPDATE** uh some linters failed - @Murderlon you can just check if wording seems fine if you'll be reviewing it today, I'll merge myself tomorrow after fixing the linters.

/docs/dashboard - remove `autoOpenFileEditor`, add `autoOpen`

---

docs/uppy-core.mdx
package.json
src/components/HomepageFeatures/index.tsx
src/components/QuickStartLinks/QuickStartLinks.tsx
src/pages/examples.tsx
src/pages/index.tsx
src/theme/BlogPostItem/Footer/index.js
src/theme/Footer/index.js

And add `--max-warnings=0` so they don't come back

meta: fix linter warnings

---

package.json
yarn.lock

Bump Yarn version, and npm deps.

meta: bump dev dependencies

---

docs/companion.md

see discussions in https://github.com/transloadit/uppy/issues/4271

improve companion docs

---

src/pages/index.tsx

I just updated the Vue example because it still used Vue's old options api.

feat: update home page vue example

---

docusaurus.config.js

Ref: https://github.com/transloadit/uppy/pull/5321
> [!CAUTION]
> Do not merge before 4.0 is released.

Add aws-s3-multipart -> aws-s3 redirect

---

src/theme/Footer/index.js

add dynamic year and range

---

docs/sources/companion-plugins/google-drive-picker.mdx
docs/sources/companion-plugins/google-photos-picker.mdx

which options to use
someone was complaining that it was a bit unclear

make it more clear

---

docs/uploader/transloadit.mdx

i didn't like the way it said that you have to "worry about creating a template"

less worry

---

docs/user-interfaces/dashboard.mdx

Add missing events to dashboard docs

---

docs/guides/choosing-uploader.md

Fix 404 link

---

docs/framework-integrations/nextjs.mdx

This fixes #352 
Please look into the #352 issue comments I've explained the cause and approach there.

Fix: api routes example for nextjs

---

docs/framework-integrations/_hooks-shared.mdx

closes #363 , should we now add all the stackblitz embeds ? 🤔

document useScreenCapture
